service:
  name: "go_polls"
  server:
    address: "localhost"
    port: 8080
    timeout:
      read: 10
      write: 100
      readHeader: 3
      idle: 10
  log:
    buildInfo : true
    level: "debug"